version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 99
  labels:
  - dependencies
  ignore:
  - dependency-name: xo
    versions:
    - 0.37.1
    - 0.38.0
    - 0.38.1
    - 0.38.2
  - dependency-name: file-type
    versions:
    - 16.2.0
  - dependency-name: globby
    versions:
    - 11.0.2
  - dependency-name: tempy
    versions:
    - 1.0.0
  - dependency-name: imagemin-svgo
    versions:
    - 8.0.0
